[project]
name = 'Supply-Chain-Quality-Assurance-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.incentive-token]
path = 'contracts/incentive-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.iot-data]
path = 'contracts/iot-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-registry]
path = 'contracts/product-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-check]
path = 'contracts/quality-check.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
